# Training config
training:
  epochs: 1000
  batch_size: 32
  loss_combine_sources: yes
  loss_use_multidomain: yes
  mix_coef: 10.0
  val_dur: 6.0
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  patience: 1000
  lr_decay_patience: 80
  lr_decay_gamma: 0.3
  weight_decay: 0.00001
# Data config
data:
  train_dir: /dev/shm/mimii
  split: 6dB
  output: /hdd/hdd1/lyj/xumx/output_wo_cont_slider_id46_test2
  sample_rate: 16000
  num_workers: 4
  seed: 42
  seq_dur: 6.0
  samples_per_track: 2
  source_augmentations:
    - gain
    - delay
  sources:
    - id_04
    - id_06
  use_control: False
  task_random: True
  source_random: False
# Network config
model:
  pretrained: null
  bidirectional: yes
  window_length: 4096
  in_chan: 4096
  nhop: 1024
  hidden_size: 512
  bandwidth: 16000
  nb_channels: 2
  spec_power: 1
